language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq swig
install:
    - pip install -r requirements.txt --use-mirrors
    # SSLv2 was removed from OpenSSL since the latest M2Crypto release...
    - pip install --upgrade git+https://github.com/msabramo/M2Crypto.git@1de89f579e5377412fd428fb96edbfd3ef4e5c4d
script: python setup.py test
